version: '3.7'

services:
    app:
        container_name: myapp
        restart: unless-stoped
        environment:
            - TZ=Asia/Seoul
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - 8000:80
        tty: true
        volumes:
            - ./web:/home/myapp
