version: '3.3'

services:
    nginx_proxy:
        image: nginx:latest
        container_name: nginx_proxy
        restart: "on-failure"
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/build:/usr/share/nginx/html

    frontend:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - 3000:3000
        volumes:
            - './frontend:/frontend'
        tty: true

    server:
        build:
            context: ./backend/
        container_name: backend
        restart: "on-failure"
        expose:
            - 8080
        volumes:
            - './backend:/backend'
            - '/backend/node_modules'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true
