version: '3.3'

services:
    nginx_proxy:
        image: nginx:latest
        container_name: nginx
        restart: "on-failure"
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        volumes:
            - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/default.conf
            - ./frontend/build:/usr/share/nginx/html
        networks:
            - frontend

    frontend:
        build:
            context: ./frontend/
        container_name: frontend
        volumes:
            - './frontend:/frontend'
        tty: true
        networks:
            - frontend

    server:
        build:
            context: ./backend/
        container_name: backend
        restart: "on-failure"
        expose:
            - 8080
        volumes:
            - './backend:/backend'
            - '/backend/node_modules'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true

networks:
    frontend:
        driver: bridge
