version: "3.7"

services:
    postgres:
        user: root
        image: postgres:13.4
        restart: unless-stoped
        ports:
            - '5432:5432'
        networks:
            - sonarnet
        container_name: postgres
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
            - POSTGRES_DB=sonar
        volumes:
            - ./volume/postgresql/data:/var/lib/postgresql/data

    sonarqube:
        user: root
        image: sonarqube:8.9.2-community
        restart: unless-stoped
        ports:
            - '9001:9001'
        networks:
            - sonarnet
        container_name: sonarqube
        environment:
            - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonar
        volumes:
            - ./volume/sonarqube_conf:/opt/sonarqube/conf
            - ./volume/sonarqube_data:/opt/sonarqube/data
            - ./volume/sonarqube_logs:/opt/sonarqube/logs
            - ./volume/sonarqube_extensions:/opt/sonarqube/extensions

networks:
    sonarnet:
        driver: bridge

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    sonarqube_temp:
    postgresql:
    postgresql_data:
